name: Auto PR de Branch 1 a Branch 2

on:
  pull_request:
    types: [opened]
    branches:
      - ms-documents-bs
  workflow_dispatch:

jobs:
  crear-pr-automatico:
    if: github.event_name == 'workflow_dispatch' || github.head_ref == 'ms-documents-bs' || github.head_ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Crear PR a ms-documents-bs-final
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Promoci칩n autom치tica desde ms-documents-bs"
          branch: auto-promote/ms-documents-bs
          base: ms-documents-bs-final
          title: "PR autom치tico desde ms-documents-bs"
          body: "Este PR fue generado autom치ticamente para promover cambios."

